### PR TITLE
Improvements in currency models

### PR DESCRIPTION
**Pull request by iPablo**
Added unique attribute to code and name fields
Added db_index to code, name and symbol fields

### CODE REVIEW

**Comment by einarf** [comment]
Might fit better in the develop branch since migrations (south and django migrations) were added there recently.

**Comment by iPablo** [comment]
Okey, I will make it in the develop branch. Could you launch a new release at pypi? I saw that you have a lot of changes between master and develop.

Thanks in advance

**Comment by einarf** [comment]
That's up to @bashu and @panosl.

But yes.. what is in master and pypi now is very outdated.

**Comment by bashu** [comment]
closed via @b09d368829e9c9fb4f5a3d63cf6b824108dc4457

**Pull request closed without merging**
