### PR TITLE
removing nonsense from app

### PR DESCRIPTION
**Pull request by bashu**
@panosl those changes was very project specific and I think they should be removed from the app. django-currencies should do one thing and do it well

### CODE REVIEW

**Comment by racitup** [comment]
@bashu I think it's fairly clear that you have a conflict of interest with your competing [module](https://github.com/bashu/django-simple-currencies) so my suggestion would be that you leave the maintenance of this.
django-currencies does do one thing and does do it well, and is intended to be feature rich. Your module is entitled **simple** so I suggest if you want to remove extraneous features that others find useful, you do it on your own module.
Plus I find your description of _nonsense_ insulting.

**Comment by bashu** [comment]
@racitup fuck off

**Comment by racitup** [comment]
> @racitup fuck off

What a lovely person you are, clearly rational and able to have a reasoned discussion.

**Comment by einarf** [comment]
You are probably right that the feature is a bit specific, but in open source you got to be more diplomatic. The feature has been around for a while and people are using it. Just purging it is not the right way to go. This would be something to figure out for the next major release.

**Comment by panosl** [comment]
@bashu you've helped a lot a while back and @racitup is doing amazing work. I don't it's worth losing our cool over a project. This is supposed to be fun and helpful.

There's no need to speak to each other in such a way.

Since it doesn't bog down the project, we can keep it around. If it fails to keep up with the rest of it, we might remove it in the future.

Maybe have a contrib section for all the extra cool stuff that are supported.

Cheers!

**Pull request closed without merging**
