### PR TITLE
Tag showing currency with optional number of decimals

### PR DESCRIPTION
**Pull request by einarf**
Added a new tag `show_currrency` that could be an alternative to the `currency` filter. This was done because multiple parameters to django template filters is a bit awkward.

Example:
`
{% show_currency price code 3 %}
`
Would render the price with 3 decimals. I shuffled things around in utils to make this possible.

Don't hesitate to comment if something is suboptimal as this was done in a hurry. I'm happy to make improvements. Adding a test for this is one obvious improvement.

(I ran tests and they passed, but I guess there is no TravisCI set up here)

### CODE REVIEW

**Comment by einarf** [comment]
Includes test and a sanity check on rounding. The rounding can get a bit too aggressive with lower than 2 decimals IMHO.

**Comment by panosl** [comment]
Not sure how I feel about another tag in the lib, are you sure we can't have that pushed into the main tag?

**Comment by einarf** [comment]
@panosl I'm using the current filter but didn't find a clean way to pass multiple parameters. I'll take another look later today.

**Comment by panosl** [comment]
Great @einarf let me know how it goes and if you need help with it.

**Comment by einarf** [comment]
@panosl  Looked at it again. The problem was that template filters do not support multiple parameters.

You can of course hack in something really awkward like:
```
{{ price|currency:"USD,3" }}
```
.. checking for comma and split the string if present. The more problematic part is when the currency is a variable as well.
```
{{ price|currency:curr.code }}
```
I guess the conclusion is that an actual tag solves the problem as they can take multiple parameters. (Both the currency and number of decimals). I understand the concern about adding more to the tag library, but I don't think there is a way around it.

**Comment by panosl** [comment]
Ok, fix the conflicts on .gitignore and I'll merge this. We can always refine it later, thanks for your contribution!

**Comment by einarf** [comment]
@panosl done!

**Pull request merged**
